spring:
  application:
    name: social-marketing

file:
  max-size: 5242880
  accept-mime-types:
    - image/jpeg
    - image/png
    - image/webp

clerk:
  webhook:
    secret: ${CLERK_WEBHOOK_SECRET}

logging:
  level:
    root: INFO
    com.social.marketing: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"